name: Despliegue

on:
  push:
    branches: [main]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v3

      - name: 🐝 Usar Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: 🔨 Hacer build
        run: |
          npm install
          npm run build
      - name: 🦅 Enviar por FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.DOMINIO }}
          username: ${{ secrets.USUARIO }}
          server-dir: colev/pronostico-covid19/
          protocol: ftps
          port: 22
          local-dir: ./publico/
          password: ${{ secrets.CLAVE }}
