name: Despliegue

on:
  push:
    branches: [main]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐝 Usar Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: 🐻 Instalar dependencias
        run: yarn install --frozen-lockfile

      - name: 🦒 Crear archivos del sitio
        run: yarn build

      - name: 🦅 Sincronizar archivos con el servidor
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LLAVE_SSH }}
          REMOTE_HOST: ${{ secrets.DOMINIO }}
          REMOTE_USER: ${{ secrets.USUARIO }}
          SOURCE: 'publico/'
          TARGET: ${{ secrets.RUTA }}
